export const projects = {
  prism: { title:'Prism AI', tags:['AI','Product','Design System'], role:'Product design · Design systems', year:'2025—Now', summary:'A flexible AI workspace that turns complex campaign decisions into clear, collaborative actions.', challenge:'Designing a system for AI products meant making intelligence feel legible, calm, and useful at every step.', approach:'I mapped the core decision-making loops, then built a modular visual language around progressive disclosure. The system gives people control without making them manage the model.', result:'A reusable foundation for a family of AI tools, with components and interaction patterns that scale from a single prompt to an entire workflow.' },
  adroom: { title:'Adroom', tags:['AI','Product','Mobile'], role:'Product design · Mobile', year:'2024', summary:'A mobile-first creative room for turning ideas into high-performing ad variations.', challenge:'Give marketers a fast way to move from a rough thought to a library of useful creative directions.', approach:'I focused the experience around an expressive canvas, quick iteration, and lightweight feedback loops that make AI feel like a collaborator.', result:'A more direct creative workflow, designed to keep momentum intact from brief to publish.' },
  sidegigs: { title:'Sidegigs', tags:['Product','Mobile'], role:'Product design · UX strategy', year:'2023', summary:'A mobile marketplace for discovering small, flexible ways to earn and contribute.', challenge:'Make an unfamiliar category feel trustworthy, human, and easy to explore.', approach:'I shaped the product around intent rather than listings: what someone can do, when they can do it, and why it matters.', result:'A clear, approachable foundation for matching people with opportunities that fit their lives.' },
  pixis: { title:'Pixis Design System', tags:['Design System','AI'], role:'Design systems · Product strategy', year:'2023—Now', summary:'A shared language for building the next generation of AI-powered marketing products.', challenge:'Unify a rapidly growing suite of tools without flattening the character of each product.', approach:'I worked across foundations, components, and contribution patterns to make consistency easy and adoption practical.', result:'A design system that connects teams, accelerates prototyping, and gives AI interactions a coherent point of view.' },
  creative: { title:'AI Creative Platform', tags:['Web','Product'], role:'Product design · Web', year:'2022', summary:'A web platform for generating, reviewing, and learning from creative work at scale.', challenge:'Bring generation and evaluation together in a workflow that feels focused instead of overwhelming.', approach:'I designed a loop between making, comparing, and learning, giving teams the context they need to make better creative decisions.', result:'A more connected path from idea to insight.' },
  dashboards: { title:'Product Dashboards', tags:['Web','UX'], role:'UX design · Information architecture', year:'2022', summary:'A set of dashboard patterns that make performance data easier to understand and act on.', challenge:'Turn dense, high-stakes information into a surface that supports quick confidence.', approach:'I simplified the hierarchy around questions, not metrics, and created a flexible system for states, filters, and comparisons.', result:'Dashboards that communicate the story behind the numbers, not just the numbers themselves.' },
  swaram: { title:'Swaram AI', tags:['Tool','AI'], role:'Independent experiment', year:'2025', summary:'An exploration of how voice, language, and AI can help people think out loud.', challenge:'Explore an AI interaction that feels more like a creative instrument than a chat window.', approach:'I prototyped a voice-first loop with generous feedback, visible context, and room for ambiguity.', result:'A small but useful experiment in making AI interaction feel more natural and expressive.' },
  coding: { title:'AI Coding Experiments', tags:['Tool','Dev','AI'], role:'Prototyping · Open source', year:'Ongoing', summary:'Small tools for exploring how designers can work directly with code and AI.', challenge:'Reduce the gap between a visual idea and a working prototype.', approach:'I build small, opinionated experiments that make the feedback loop between design and code faster.', result:'A growing set of techniques for thinking, making, and learning in public.' },
  'side-projects': { title:'Side Projects', tags:['Web','Product'], role:'Independent design & development', year:'Ongoing', summary:'A collection of useful, curious, and occasionally weird things built outside the day job.', challenge:'Make space for ideas that do not need a roadmap to become real.', approach:'Start small, ship early, and let the interaction teach me what the product wants to be.', result:'A practice of staying close to making.' },
  terminal: { title:'Terminal & CLI Experiments', tags:['Code','Open Source'], role:'Code · Tooling', year:'Ongoing', summary:'Command-line tools and tiny utilities for a more tactile digital workflow.', challenge:'Find moments where a simple command can make a complex task feel direct.', approach:'I use the terminal as a playground for interfaces, automation, and small acts of leverage.', result:'A practical archive of experiments that keep engineering close to the design process.' },
  'brand-refresh': { title:'Brand Refresh Plugin', tags:['Brand','Tool'], role:'Brand design · Plugin design', year:'2026', summary:'A focused tool for bringing brand clarity into everyday creative workflows.', challenge:'Make brand consistency easier to maintain while people move quickly.', approach:'I explored lightweight guidance, reusable assets, and context-aware prompts that support the work without interrupting it.', result:'A practical brand tool that helps teams make confident, on-brand decisions.' },
  'employer-award': { title:'2X Employer Awards', tags:['Award'], role:'Recognition', year:'2024—2025', summary:'Recognition for contribution, collaboration, and impact across the team.', challenge:'Show up with consistency, curiosity, and care in the work and in the relationships around it.', approach:'I bring design thinking, engineering fluency, and a bias toward making useful things together.', result:'Two moments of recognition that reflect the culture and people I have had the chance to work with.' },
  mystop: { title:'MyStop', tags:['UX','Case Study'], role:'Product design · UX', year:'2021', summary:'A focused product experience designed to help people find their next step with less friction.', challenge:'Make a practical everyday task feel clear, quick, and dependable.', approach:'I shaped the experience around strong wayfinding, useful defaults, and simple moments of confirmation.', result:'A calm product flow that gets people where they need to go.' },
  visibility: { title:'Visibility', tags:['Marketing','AI'], role:'Product design · UX strategy', year:'2021', summary:'A product concept for making progress, context, and important information easier to see.', challenge:'Turn scattered information into a shared understanding for the people using it.', approach:'I organized the experience around visibility of status, ownership, and next actions.', result:'A clearer view of the work and the decisions around it.' },
  'care-io': { title:'Care.io', tags:['UX','Case Study'], role:'Product design · Digital health', year:'2020', summary:'A thoughtful digital experience for navigating care with more confidence and continuity.', challenge:'Make a sensitive, complex journey feel more human and easier to move through.', approach:'I focused on clarity, reassurance, and progressive disclosure across the key moments of the experience.', result:'A more supportive path through care-related tasks and information.' }
};
